Repository liborioc1/Instagram_SOEN341, pull requests merged in 2021-04, with the labels that each got.

#92 #81 #85 Implemented modal for selected posts on user profiles to view…
  .eslintcache
  src/Components/ImageGrid.js
  src/Components/Modal.css
  src/Components/Modal.js
  src/Components/PostLayout.js
Labels: Back-End, Front-End, In Progress

#95 #81 #85 #93 #94 Fixed Single Character Bug in Popup TextField + Refac…
  .eslintcache
  src/Components/ConditionalButtons/FollowButton.js
  src/Components/ConditionalButtons/UploadButton.js
  src/Components/Forms/SignInBox.css
  src/Components/Forms/SignInBox.js
  src/Components/Forms/SignUpBox.css
  src/Components/Forms/SignUpBox.js
  src/Components/Grids/ImageGrid.css
  src/Components/Grids/ImageGrid.js
  src/Components/Headers/Header.js
  src/Components/Headers/HeaderProfile.js
  src/Components/Headers/Menu.js
  src/Components/Modals/ListModal.js
  src/Components/Modals/ListModalProfile.js
  src/Components/Modals/Modal.css
  src/Components/Modals/Modal.js
  src/Components/Modals/UploadModal.css
  src/Components/Modals/UploadModal.js
  src/Components/Modals/UploadedForm.css
  src/Components/Posts/PostLayout.css
  src/Components/Posts/PostLayout.js
  src/Firebase/Authenticated.js
  src/Firebase/firebase.js
  src/Hooks/useFirestore.js
  src/Pages/Feed.js
  src/Pages/PersonalProfile.js
  src/Pages/Profile.js
  src/Pages/SignIn.js
  src/Pages/SignUp.js
  src/Router/App.css
  src/Router/App.js
  src/Router/PrivateRoute.js
  src/TestUtilities/SignUpTest-utils.js
  src/TestUtilities/test-utils.js
  src/__tests__/feedTest.js
  src/__tests__/personalProfileTest.js
  src/__tests__/profileTest.js
  src/__tests__/signInTest.js
  src/__tests__/signUpTest.js
  src/index.js
Labels: Back-End, Fix, Front-End, Refactoring

#96 #81 #84 Fixed the bug for the followers and following list modals
  .eslintcache
  src/Components/Modals/ListModalProfile.js
  src/Pages/Profile.js
Labels: Back-End

#97 #55 #58 Test feed implemented
  .eslintcache
  src/Components/Headers/Header.js
  src/__tests__/feedTest.js
Labels: Testing

#100 #81 #85 #99 Designed the Popup for the Profile Page (comments, spacin…
  .eslintcache
  src/Components/Headers/Header.js
  src/Components/Modals/Modal.css
  src/Components/Modals/Modal.js
  src/Components/Posts/PostLayout.css
  src/__tests__/feedTest.js
Labels: Front-End

#102 #101 Updated Readme with additional feature
  README.md
Labels: Documentation

#103 #101 Updated ReadMe Techniques
  README.md
Labels: Documentation

#105 #104 Fixed Bug for User Profile Details Occasionally not Showing
  .eslintcache
  src/Components/Headers/Header.js
  src/Pages/Profile.js
Labels: Fix
