Repository liborioc1/Instagram_SOEN341, pull requests merged in 2021-03, with the labels that each got.

#74 #4 #69 #70 #71 #73 Updated Personal Profile/Profile Page UI + Created…
  .eslintcache
  src/Components/FollowButton.js
  src/Components/Header.js
  src/Components/Menu.js
  src/Components/PostLayout.css
  src/Components/ProgressBar.js
  src/Components/UploadButton.js
  src/Components/UploadModal.js
  src/Components/UploadedForm.js
  src/Pages/PersonalProfile.css
  src/Pages/PersonalProfile.js
  src/Pages/Profile.css
  src/Pages/Profile.js
Labels: Back-End, Fix, Front-End

#75 #7 #23 #31 Added the timestamp to the comments & fixed a warning for …
  .eslintcache
  src/Components/PostLayout.css
  src/Components/PostLayout.js
Labels: Fix, Front-End

#76 #7 #23 #31 #66 #67 Modified feed to remove gray bar if no posts are l…
  .eslintcache
  public/images/FeedNotification.png
  src/Components/PostLayout.css
  src/Components/PostLayout.js
  src/Pages/Feed.css
  src/Pages/Feed.js
Labels: Back-End, Front-End

#77 #46 #68 Removed Search Bar from Profile and Personal Profile pages an…
  .eslintcache
  public/images/dino.png
  src/Components/Header.js
  src/Components/HeaderProfile.js
  src/Pages/Error.css
  src/Pages/Error.js
  src/Pages/PersonalProfile.js
  src/Pages/Profile.js
Labels: Fix, Front-End

#78 #7 #66 Updated the font family and font style of the post layout
  .eslintcache
  src/Components/PostLayout.css
  src/Components/PostLayout.js
Labels: Front-End

#79 #55 #60 Create test cases for Personal Profile Page
  .eslintcache
  package-lock.json
  package.json
  src/Components/Header.js
  src/Components/HeaderProfile.js
  src/Components/ImageGrid.js
  src/Components/Menu.js
  src/__tests__/personalProfileTest.js
  src/test-utils.js
Labels: Testing

#80 #55 #57 #60 Implemented SignUp page tests and fixed PersonalProfileTe…
  .eslintcache
  src/Components/SignInBox.js
  src/Components/SignUpBox.js
  src/Pages/SignUp.js
  src/SignUpTest-utils.js
  src/__tests__/personalProfileTest.js
  src/__tests__/signInTest.js
  src/__tests__/signUpTest.js
Labels: Fix, Testing

#86 #82 Reviewed and Renamed Variable names to follow CamelBack naming co…
  .eslintcache
  src/Components/Header.js
  src/Components/HeaderProfile.js
  src/Components/ImageGrid.js
  src/Components/PostLayout.css
  src/Components/PostLayout.js
  src/Components/ProgressBar.css
  src/Components/SignInBox.css
  src/Components/UploadModal.js
  src/Pages/Error.css
  src/Pages/Error.js
  src/Pages/Feed.css
  src/Pages/Feed.js
  src/Pages/SignIn.js
Labels: Refactor

#87 #55 #59 Created Travis CI Tests for Profile Page
  .eslintcache
  src/Components/FollowButton.js
  src/Components/UploadModal.js
  src/Pages/Profile.js
  src/__tests__/profileTest.js
  src/__tests__/signUpTest.js
Labels: Testing

#89 #81 #83 #84 Following and followers lists implemented in clickable bu…
  .eslintcache
  src/Components/ImageGrid.js
  src/Components/ListModal.js
  src/Components/ListModalProfile.js
  src/Pages/PersonalProfile.js
  src/Pages/Profile.js
  src/Pages/SignUp.js
  src/__tests__/personalProfileTest.js
  src/__tests__/profileTest.js
Labels: Back-End, Database, Front-End

#90 #5 #83 Updated UI of Following/Follower Button
  .eslintcache
  src/Components/ListModal.js
  src/Components/ListModalProfile.js
  src/Components/UploadModal.js
  src/Pages/Profile.css
  src/__tests__/profileTest.js
Labels: Front-End

#91 #55 #56 #57 test cases for signIn page (password and email validation…
  src/Components/SignInBox.js
  src/Pages/SignIn.js
  src/Pages/SignUp.js
  src/__tests__/signInTest.js
  src/__tests__/signUpTest.js
Labels: Testing
