Repository liborioc1/Instagram_SOEN341, pull requests merged in 2021-02, with the labels that each got.

#34 #2 #8 #10 #17 Firebase Authentication Implemented for Sign In/Sign Up + Updated Routing (PrivateRoutes)
  .eslintcache
  src/App.js
  src/Authenticated.js
  src/Components/HeroSection.css
  src/Components/HeroSection.js
  src/Components/SignInBox.css
  src/Components/SignInBox.js
  src/Components/SignUpBox.js
  src/Pages/Feed.js
  src/Pages/SignIn.js
  src/Pages/SignUp.js
  src/PrivateRoute.js
  src/firebase.js
Labels: Back-End

#36 #5 #6 #20 #21 Access to local files + Upload image to database + Init…
  .eslintcache
  package-lock.json
  package.json
  src/Authenticated.js
  src/Components/Header.js
  src/Components/ImageGrid.css
  src/Components/ImageGrid.js
  src/Components/Modal.css
  src/Components/Modal.js
  src/Components/ProgressBar.css
  src/Components/ProgressBar.js
  src/Components/SignInBox.js
  src/Components/UploadedForm.css
  src/Components/UploadedForm.js
  src/Hooks/useFirestore.js
  src/Hooks/useStorage.js
  src/Pages/Feed.js
  src/Pages/Profile.css
  src/Pages/Profile.js
  src/Pages/SignIn.js
  src/Pages/SignUp.js
  src/firebase.js
Labels: Back-End, Database, Done, Front-End

#38 #2 #15 #35 Handled uniqueness of username + users stored in database
  .eslintcache
  src/Components/SignUpBox.js
  src/Pages/SignUp.js
Labels: Back-End, Database, Done

#39 #3 #5 Posts Layout and Feed Page Layout implemented
  .eslintcache
  src/Components/Header.js
  src/Components/PostLayout.js
  src/Pages/Feed.css
  src/Pages/Feed.js
  src/Pages/Profile.js
  src/static/posts.js
Labels: Front-End, In Progress

#41 #6 #18 #22 #25 #27 #29 #30 #37 Pair programming with @liborioc1 via Live Share...
  .eslintcache
  package-lock.json
  package.json
  src/App.js
  src/Components/FollowButton.js
  src/Components/Header.js
  src/Components/PostLayout.js
  src/Pages/Feed.css
  src/Pages/Feed.js
  src/Pages/PersonalProfile.js
  src/Pages/Profile.js
  src/Pages/SignIn.js
  src/Pages/SignUp.js
  src/__tests__/feedTest.js
  src/__tests__/personalProfileTest.js
  src/__tests__/profileTest.js
  src/__tests__/signInTest.js
  src/__tests__/signUpTest.js
  src/firebase.js
  src/setupTests.js
  src/static/posts.js
  src/travis.yml
Labels: Back-End, Database, Front-End, In Progress

#43 #42 Renamed travis.yml to .travis.yml
  src/.travis.yml
Labels: Fix

#44 #42 Moved the .travis.yml file to root directory
  .travis.yml
Labels: Fix

#45 #5 #19 #24 #32 #40 Created upload pop so that images can be uploaded …
  .eslintcache
  public/images/logo.png
  public/images/logo2.png
  public/images/logo3.png
  public/images/logo4.png
  public/videos/Clouds.mp4
  src/Components/Header.js
  src/Components/ImageGrid.js
  src/Components/Modal.css
  src/Components/PostLayout.js
  src/Components/ProgressBar.js
  src/Components/SignInBox.css
  src/Components/SignInBox.js
  src/Components/SignUpBox.js
  src/Components/UploadModal.css
  src/Components/UploadModal.js
  src/Components/UploadedForm.css
  src/Components/UploadedForm.js
  src/Hooks/useFirestore.js
  src/Hooks/useStorage.js
  src/Pages/Error.js
  src/Pages/Feed.css
  src/Pages/Feed.js
  src/Pages/PersonalProfile.js
  src/Pages/Profile.js
  src/Pages/SignIn.js
  src/Pages/SignUp.js
Labels: Back-End, Database, Front-End, In Progress

#47 #5 #21 #30 Updated the profile page and Header layouts (including the…
  .eslintcache
  public/images/circle.png
  src/Components/Header.js
  src/Components/ImageGrid.css
  src/Components/PostLayout.js
  src/Components/SignUpBox.css
  src/Components/SignUpBox.js
  src/Components/UploadModal.css
  src/Pages/Feed.js
  src/Pages/PersonalProfile.css
  src/Pages/PersonalProfile.js
Labels: Front-End, In Progress

#48 #5 #12 #16 Updated a dynamic feed, and post layout
  src/Pages/Feed.js
Labels: Back-End, Done, Fix, Front-End

#50 #5 #12 #16 FIX dynamic feed, and post layout.
  .eslintcache
  package-lock.json
  package.json
  src/Components/Header.js
  src/Components/PostLayout.css
  src/Components/PostLayout.js
  src/Pages/Feed.css
  src/static/posts.js
Labels: Done, Fix, Front-End

#52 #5 #6 #11 #26 #49 #51 Adjusted Infinite Database Calls and Timestamp …
  .eslintcache
  package-lock.json
  package.json
  src/Components/Header.js
  src/Components/ImageGrid.js
  src/Components/PostLayout.css
  src/Components/PostLayout.js
  src/Pages/PersonalProfile.js
  src/Pages/Profile.js
  src/Pages/SignUp.js
Labels: Back-End, Database, Fix, Front-End

#62 #5 #61 Fixed upload bug when no image is selected when upload button…
  .eslintcache
  package-lock.json
  src/Components/PostLayout.js
  src/Components/UploadButton.js
  src/Components/UploadModal.js
  src/Pages/Feed.js
Labels: Back-End, Database

#63 #5 #6 #11 #19 loads posts onto feed according to following
  .eslintcache
  src/Pages/Feed.js
Labels: Back-End, Database

#65 #6 #25 #64 Fixed Follow Button Not appearing for Person that the User…
  .eslintcache
  src/Pages/Profile.js
Labels: Done, Fix, Front-End

#72 #7 #23 #28 #31 Post comments implemented
  .eslintcache
  src/Components/PostLayout.css
  src/Components/PostLayout.js
  src/Pages/Feed.js
Labels: Back-End, Database, Done, Front-End
